import type { Metadata } from "next";
// import localFont from "next/font/local";
import ThemeProvider from "@/providers/Theme";
import "@/styles/global.css";
import { Header } from "@/components/layout/Header";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{height: '100%'}}>
      <ThemeProvider>
        <Header />
        {children}
      </ThemeProvider>
    </html>
  );
}
